name: MATLAB Automated Testing

on: [push] 

jobs:
  run-my-simulations:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run simulations
        uses: matlab-actions/run-command@v2
        with:
          command: run_tests 
