name: MATLAB Automated Testing

on:
  push:
    branches: [ "disc-event-sim"] 
  pull_request:
    branches: [ "disc-event-sim"]

jobs:
  run-simulations:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run my selected tests
        uses: matlab-actions/run-command@v2
        with:
          command: run_selected_tests
